# Site settings
title: My Portfolio
description: A blog about my passions and project history
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jtbryan.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jonathan Bryan
user_description: I am a passionate software developer with a primary focus in Back-End and Full Stack development as well as a fascination for Cybersecurity and Data Science
user_title: Software Developer
email: jonnib24@gmail.com
github_username:  jtbryan

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
